// 函数: sub_14048d860
// 地址: 0x14048d860
// 来自: E:\Embers\Embers\Binaries\Win64\Embers-Win64-Shipping.exe

int64_t* rcx = data_143db18d0

if (rcx == 0)
    sub_140a53c40()
    rcx = data_143db18d0

data_143e81860 = (*(*rcx + 0x38))(rcx, r.Cache.DrawLightingSamples", &data_143e813b0, Whether to "
"draw indirect lighting sample points as generated by Lightmass.\n0 is off (default), 1 is on"
    , 0x20)
data_143e81858 = &data_142d3ff10
return atexit(sub_142cd79a0) __tailcall
