// 函数: sub_142317220
// 地址: 0x142317220
// 来自: E:\Embers\Embers\Binaries\Win64\Embers-Win64-Shipping.exe

switch (arg1)
    case 0
        return u"BrushWireframe"
    case 1
        return u"Wireframe"
    case 2
        return u"Unlit"
    case 3
        return &data_143326ea8
    case 4
        return u"Lit_DetailLighting"
    case 5
        return u"LightingOnly"
    case 6
        return u"LightComplexity"
    case 8
        return u"ShaderComplexity"
    case 9
        return u"LightmapDensity"
    case 0xa
        return u"LitLightmapDensity"
    case 0xb
        return u"ReflectionOverride"
    case 0xc
        return u"VisualizeBuffer"
    case 0xe
        return u"StationaryLightOverlap"
    case 0xf
        return u"CollisionPawn"
    case 0x10
        return u"CollisionVis"
    case 0x12
        return u"LODColoration"
    case 0x13
        return u"QuadOverdraw"
    case 0x14
        return u"PrimitiveDistanceAccuracy"
    case 0x15
        return u"MeshUVDensityAccuracy"
    case 0x16
        return u"ShaderComplexityWithQuadOverdraw"
    case 0x17
        return u"HLODColoration"
    case 0x19
        return u"MaterialTexturecaleAccuracy"
    case 0x1a
        return u"RequiredTextureResolution"
    case 0x1b
        return u"PathTracing"
    case 0x1c
        return u"RayTracingDebug"
    case 0xff
        return u"Unknown"

return &data_142d40450
