// 函数: sub_14048d780
// 地址: 0x14048d780
// 来自: E:\Embers\Embers\Binaries\Win64\Embers-Win64-Shipping.exe

int64_t* rcx = data_143db18d0

if (rcx == 0)
    sub_140a53c40()
    rcx = data_143db18d0

data_143e81870 = (*(*rcx + 0x38))(rcx, r.Cache.DrawDirectionalShadowing", &data_143e813b4, Whether "
"to draw direct shadowing sample points as generated by Lightmass.\n0 is off (default), 1 is on"
    , 0x20)
data_143e81868 = &data_142d3ff10
return atexit(sub_142cd7900) __tailcall
