// 函数: sub_140b5fcb0
// 地址: 0x140b5fcb0
// 来自: E:\Embers\Embers\Binaries\Win64\Embers-Win64-Shipping.exe

if (arg1 s<= 0xc8)
    switch (arg1)
        case 0
            return u"None"
        case 1
            return u"ByteProperty"
        case 2
            return u"IntProperty"
        case 3
            return u"BoolProperty"
        case 4
            return u"FloatProperty"
        case 5
            return u"ObjectProperty"
        case 6
            return u"NameProperty"
        case 7
            return u"DelegateProperty"
        case 8
            return u"DoubleProperty"
        case 9
            return u"ArrayProperty"
        case 0xa
            return u"StructProperty"
        case 0xb
            return u"VectorProperty"
        case 0xc
            return u"RotatorProperty"
        case 0xd
            return u"StrProperty"
        case 0xe
            return u"TextProperty"
        case 0xf
            return u"InterfaceProperty"
        case 0x10
            return u"MulticastDelegateProperty"
        case 0x12
            return u"LazyObjectProperty"
        case 0x13
            return u"SoftObjectProperty"
        case 0x14
            return u"Int64Property"
        case 0x15
            return u"Int32Property"
        case 0x16
            return u"Int16Property"
        case 0x17
            return u"Int8Property"
        case 0x18
            return u"UInt64Property"
        case 0x19
            return u"UInt32Property"
        case 0x1a
            return u"UInt16Property"
        case 0x1c
            return u"MapProperty"
        case 0x1d
            return u"SetProperty"
        case 0x1e
            return u"Core"
        case 0x1f
            return u"Engine"
        case 0x20
            return u"Editor"
        case 0x21
            return u"CoreUObject"
        case 0x22
            return u"EnumProperty"
        case 0x32
            return u"Cylinder"
        case 0x33
            return u"BoxSphereBounds"
        case 0x34
            return u"Sphere"
        case 0x35
            return &data_142e7a7b0
        case 0x36
            return u"Vector2D"
        case 0x37
            return u"IntRect"
        case 0x38
            return u"IntPoint"
        case 0x39
            return u"Vector4"
        case 0x3a
            return u"Name"
        case 0x3b
            return u"Vector"
        case 0x3c
            return u"Rotator"
        case 0x3d
            return u"SHVector"
        case 0x3e
            return u"Color"
        case 0x3f
            return u"Plane"
        case 0x40
            return u"Matrix"
        case 0x41
            return u"LinearColor"
        case 0x42
            return u"AdvanceFrame"
        case 0x43
            return u"Pointer"
        case 0x44
            return u"Double"
        case 0x45
            return u"Quat"
        case 0x46
            return u"Self"
        case 0x47
            return u"Transform"
        case 0x64
            return u"Object"
        case 0x65
            return u"Camera"
        case 0x66
            return u"Actor"
        case 0x67
            return u"ObjectRedirector"
        case 0x68
            return u"ObjectArchetype"
        case 0x69
            return u"Class"
        case 0x6a
            return u"ScriptStruct"
        case 0x6b
            return u"Function"
        case 0xc8
            return u"State"
else if (arg1 s> 0x1f4)
    if (arg1 == 0x258)
        return u"EditorLayout"
    
    if (arg1 == 0x259)
        return u"EditorKeyBindings"
    
    if (arg1 == 0x25a)
        return u"GameUserSettings"
    
    if (arg1 == 0x2bc)
        return u"Filename"
    
    if (arg1 == 0x2bd)
        return u"Lerp"
else
    if (arg1 == 0x1f4)
        return u"PerformanceCapture"
    
    if (arg1 - 0xc9 u<= 0xfa)
        switch (arg1)
            case 0xc9
                return u"TRUE"
            case 0xca
                return u"FALSE"
            case 0xcb
                return u"Enum"
            case 0xcc
                return u"Default"
            case 0xcd
                return u"Skip"
            case 0xce
                return u"Input"
            case 0xcf
                return u"Package"
            case 0xd0
                return u"Groups"
            case 0xd1
                return u"Interface"
            case 0xd2
                return u"Components"
            case 0xd3
                return u"Global"
            case 0xd4
                return u"Super"
            case 0xd5
                return u"Outer"
            case 0xd6
                return &data_142e7a9c8
            case 0xd7
                return u"Role"
            case 0xd8
                return u"RemoteRole"
            case 0xd9
                return u"PersistentLevel"
            case 0xda
                return u"TheWorld"
            case 0xdb
                return u"PackageMetaData"
            case 0xdc
                return u"InitialState"
            case 0xdd
                return u"Game"
            case 0xde
                return u"SelectionColor"
            case 0xdf
                return &data_142e7aa90
            case 0xe0
                return u"ExecuteUbergraph"
            case 0xe1
                return u"DeviceID"
            case 0xe2
                return u"RootStat"
            case 0xe3
                return u"MoveActor"
            case 0xe6
                return &data_142dd8278
            case 0xe7
                return u"MeshEmitterVertexColor"
            case 0xe8
                return u"TextureOffsetParameter"
            case 0xe9
                return u"TextureScaleParameter"
            case 0xea
                return u"ImpactVel"
            case 0xeb
                return u"SlideVel"
            case 0xec
                return u"TextureOffset1Parameter"
            case 0xed
                return u"MeshEmitterDynamicParameter"
            case 0xee
                return u"ExpressionInput"
            case 0xef
                return u"Untitled"
            case 0xf0
                return u"Timer"
            case 0xf1
                return u"Team"
            case 0xf2
                return &data_142e7ac88
            case 0xf3
                return u"High"
            case 0xf4
                return u"NetworkGUID"
            case 0xf5
                return u"GameThread"
            case 0xf6
                return u"RenderThread"
            case 0xf7
                return u"OtherChildren"
            case 0xf8
                return u"Location"
            case 0xf9
                return u"Rotation"
            case 0xfa
                return &data_142e7ace0
            case 0xfb
                return u"EditorSettings"
            case 0xfc
                return u"AudioThread"
            case 0xfd
                return &data_142db68c4
            case 0xfe
                return u"UserDefinedEnum"
            case 0xff
                return u"Control"
            case 0x100
                return u"Voice"
            case 0x101
                return u"Zlib"
            case 0x102
                return u"Gzip"
            case 0x103
                return &data_142e7ad80
            case 0x118
                return u"DGram"
            case 0x119
                return u"Stream"
            case 0x11a
                return u"GameNetDriver"
            case 0x11b
                return u"PendingNetDriver"
            case 0x11c
                return u"BeaconNetDriver"
            case 0x11d
                return u"FlushNetDormancy"
            case 0x11e
                return u"DemoNetDriver"
            case 0x11f
                return u"GameSession"
            case 0x120
                return u"PartySession"
            case 0x121
                return u"GamePort"
            case 0x122
                return u"BeaconPort"
            case 0x123
                return u"MeshPort"
            case 0x124
                return u"MeshNetDriver"
            case 0x125
                return u"LiveStreamVoice"
            case 0x12c
                return u"Linear"
            case 0x12d
                return u"Point"
            case 0x12e
                return u"Aniso"
            case 0x12f
                return u"LightMapResolution"
            case 0x137
                return u"UnGrouped"
            case 0x138
                return u"VoiceChat"
            case 0x140
                return u"Playing"
            case 0x142
                return u"Spectating"
            case 0x145
                return u"Inactive"
            case 0x15e
                return u"PerfWarning"
            case 0x15f
                return u"Info"
            case 0x160
                return u"Init"
            case 0x161
                return u"Exit"
            case 0x162
                return &data_142e7afd0
            case 0x163
                return u"Warning"
            case 0x164
                return u"Error"
            case 0x190
                return u"FontCharacter"
            case 0x191
                return u"InitChild2StartBone"
            case 0x192
                return u"SoundCueLocalized"
            case 0x193
                return u"SoundCue"
            case 0x194
                return u"RawDistributionFloat"
            case 0x195
                return u"RawDistributionVector"
            case 0x196
                return u"InterpCurveFloat"
            case 0x197
                return u"InterpCurveVector2D"
            case 0x198
                return u"InterpCurveVector"
            case 0x199
                return u"InterpCurveTwoVectors"
            case 0x19a
                return u"InterpCurveQuat"
            case 0x1c2
                return &data_142e7b188
            case 0x1c3
                return u"NavMesh"

return u"*INVALID*"
