// 函数: sub_14051a070
// 地址: 0x14051a070
// 来自: E:\Embers\Embers\Binaries\Win64\Embers-Win64-Shipping.exe

sub_1405947f0(&data_143f3ef50, 0x1a)
int32_t rax = data_143f3ef58 + 0x1a
bool cond:0 = rax s<= data_143f3ef5c
data_143f3ef58 = rax

if (not(cond:0))
    sub_140594770(&data_143f3ef50)

UnDecorator::getReferenceType(data_143f3ef50, u"AutogeneratedDefaultValue", 0x34)
return atexit(sub_142cff870) __tailcall
