// 函数: sub_142c58d40
// 地址: 0x142c58d40
// 来自: E:\Embers\Embers\Binaries\Win64\Embers-Win64-Shipping.exe

int64_t rbp
rbp.b = 0

if (arg1 == 0 || *(arg1 + 0x14) == 0)
    return 0

sub_142c59360(arg1)
FILE* _Stream

if (0x2d != *arg2 || 0 != arg2[1])
    FILE* _Stream_1 = fopen(arg2, "wt")
    _Stream = _Stream_1
    
    if (_Stream_1 == 0)
    label_142c58e4c:
        return 1
else
    _Stream = __acrt_iob_func(1)
    rbp.b = 1

fputs(
    "# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was "
"generated by libcurl! Edit at your own risk.\n\n", 
    _Stream)

for (void** i = *arg1; i != 0; i = *i)
    if (i[5] != 0)
        int64_t rax_1
        int64_t r8_1
        int512_t zmm2_1
        rax_1, r8_1, zmm2_1 = sub_142c59100(i)
        
        if (rax_1 == 0)
            sub_142c56480(_Stream, "#\n# Fatal libcurl error\n", r8_1, zmm2_1)
            
            if (rbp.b == 0)
                fclose(_Stream)
            
            goto label_142c58e4c
        
        sub_142c56480(_Stream, "%s\n", rax_1, zmm2_1)
        data_143ccb8a0(rax_1)

if (rbp.b == 0)
    fclose(_Stream)

return 0
